### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [ZoeKHarvey/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Really good job on the assessment Zoe! This is incredibly close. We just have a few small changes we would like you to make. The attribute `total_owned` and the method `calculate_missing` somewhat break the rule of encapsulation in OOP. The idea here is that one tennis ball will not need to know about another tennis ball, so we wouldn't want to have a method or attribute that relies on data from other tennis balls. These could be good methods on the `gym_sport_ball` class if we had a database of balls and we ran a query that summed the number of `trues` on a `is_missing?` attribute. But, this is beyond the scope of Mod-0 and beyond the scope of Mod-1 even, but I wanted you to know that you are not completely off. So for the updates: Replace the attribute and the method I pointed out above with something else that does not rely on data from any other possible instances. And, delete the `top_down_design.md` file that is blank. Commit and push these changes. Send us a message with a link to your mod_0_skills repo once you've made the changes, and we will update your status. Once again - I want to reiterate that these are small changes and this is a solid assessment. Great job in Mod-0 Zoe. Reach out if you have any questions about this feedback or the instructions. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
